In [1]:
import re
import glob
import xlwings as xw
import math
from pathlib import Path
import random
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as mpl
from matplotlib import cm
import matplotlib.pyplot as plt
import matplotlib.colors as mclr
import plotly.express as px
import statsmodels.api as sm
import pylab as py
import os, cv2, glob, tempfile
import joblib

from scipy import stats
from scipy.stats import pearsonr

import sklearn
from sklearn import datasets
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import minmax_scale
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import QuantileTransformer
from sklearn.datasets import make_blobs

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import VotingClassifier
from sklearn import metrics
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import matthews_corrcoef
make_scorer = sklearn.metrics.make_scorer
f1 = make_scorer(f1_score, pos_label=1, average="binary")
from sklearn.metrics import classification_report
from sklearn.inspection import permutation_importance
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split, cross_val_score, cross_validate, KFold
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.model_selection import RepeatedStratifiedKFold

import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import BatchNormalization, Conv2D, MaxPooling2D, Activation, Dropout, Flatten, Dense
from keras.optimizers import Adam
from keras import utils as np_utils
from keras import models
import keras_tuner as kt
from scipy import signal

import config as config
print(config.__path__)
from keras.callbacks import EarlyStopping
from keras.utils import to_categorical
from keras import backend as K

import argparse
# from sklearn.utils import class_weight
print(tf.__version__)
print(keras.__version__)

import shutil
import xlwings as xw

%matplotlib inline
mpl.use("Agg")

['C:\\Users\\user\\anaconda3\\lib\\site-packages\\config']
2.12.0-dev20221107
2.12.0

In [2]:
## Build XGBoost Model
from copy import deepcopy
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.graphics.tsaplots import plot_acf,plot_pacf
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV,train_test_split
from skopt import BayesSearchCV
from sklearn.metrics import accuracy_score,f1_score,roc_auc_score,confusion_matrix,roc_curve
import xgboost as xgb
import time
import warnings

# 1. Data Preparation

In [3]:
train1011DEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\df1011prog_train_raMSIn4nonInDI_norm.csv")
train2021DEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\df2021prog_train_raMSIn4nonInDI_norm.csv")
train3031DEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\df3031prog_train_raMSIn4nonInDI_norm.csv")

In [4]:
for i in range(len(train3031DEFSDf)):
    if train3031DEFSDf.iloc[i]["type"] == 1:
        train3031DEFSDf.at[i, "type"] = 2

In [5]:
train3031DEFSDf

,pixel_id,250.1448,303.2329,295.2278,480.3099,215.0326,255.233,327.233,619.2894,865.5025,311.1688,269.2486,738.5062,435.2964,514.2848,type
0,HKULiver_Post29wk_HCCAMCLiver_Left_Mice01_Slid...,1.773653,-2.816098,-0.135375,-1.481990,-0.834750,-1.844939,-2.90304,-0.577605,-0.931716,1.746855,1.744517,-2.052740,-1.786066,-0.65104,0
1,HKULiver_Post29wk_HCCAMCLiver_Left_Mice01_Slid...,2.072552,-2.816098,-0.135375,-1.481990,-0.495775,-1.606137,-2.90304,-0.577605,-0.931716,2.118571,0.986343,-2.052740,-1.786066,-0.65104,0
2,HKULiver_Post29wk_HCCAMCLiver_Left_Mice01_Slid...,2.477552,-2.816098,-0.135375,-1.481990,-0.997282,-1.560315,-2.90304,-0.577605,-0.931716,1.974339,-0.747119,-1.258154,-1.786066,-0.65104,0
3,HKULiver_Post29wk_HCCAMCLiver_Left_Mice01_Slid...,3.007343,-2.816098,-0.135375,-1.481990,-1.312407,-1.624374,-2.90304,-0.577605,-0.931716,1.834585,1.292046,-1.304415,-1.786066,-0.65104,0
4,HKULiver_Post29wk_HCCAMCLiver_Left_Mice01_Slid...,2.022190,-2.816098,-0.135375,-1.481990,-0.730136,-1.648270,-2.90304,-0.577605,-0.931716,1.990816,-0.747119,-1.289011,-1.786066,-0.65104,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156224,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,0.118477,-2.816098,-0.135375,-1.481990,-1.583552,-1.363534,-2.90304,-0.577605,0.070234,1.720414,1.008232,-2.052740,-1.786066,-0.65104,2
156225,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,0.362748,-2.816098,-0.135375,-1.481990,-1.715775,-1.289841,-2.90304,-0.577605,-0.037978,1.342527,1.687290,-0.479456,-1.786066,-0.65104,2
156226,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,0.146787,-2.816098,-0.135375,-0.401833,-2.963623,-1.200898,-2.90304,1.367008,0.222042,1.402804,-0.747119,-0.614254,-1.786066,-0.65104,2
156227,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,-0.037829,-2.816098,-0.135375,-1.481990,-2.963623,-1.553132,-2.90304,-0.577605,-0.931716,1.468600,-0.747119,-0.985103,-1.786066,-0.65104,2
156228,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,-0.026180,-2.816098,-0.135375,-1.481990,-1.662700,-1.629699,-2.90304,-0.577605,-0.051485,1.310582,-0.747119,-0.994451,-1.786066,-0.65104,2

In [6]:
trainDEFSDf = pd.concat([train1011DEFSDf, train2021DEFSDf, train3031DEFSDf]).reset_index().drop(columns=["index"])

In [7]:
trainDEFSDf

,pixel_id,250.1448,303.2329,295.2278,480.3099,215.0326,255.233,327.233,619.2894,865.5025,311.1688,269.2486,738.5062,435.2964,514.2848,type
0,HKULiver_20wk_NormalLiver_LeftLateral_Mice01_S...,0.102481,-1.093037,-0.564945,-1.521416,-0.925045,-0.534553,-1.127449,-1.162273,-0.347642,-0.196735,-0.287714,-1.280833,-0.171629,-0.724925,0
1,HKULiver_20wk_NormalLiver_LeftLateral_Mice01_S...,0.832238,-0.790281,-0.580741,-1.521416,-0.057796,-0.067876,-0.788238,-1.162273,0.484253,-0.109089,0.190905,-0.578033,0.501930,0.579031,0
2,HKULiver_20wk_NormalLiver_LeftLateral_Mice01_S...,0.883453,-0.477117,-0.130487,-1.521416,0.192906,0.018420,-0.589604,-1.162273,0.392841,-0.179414,-0.048635,-0.493455,0.578610,-0.724925,0
3,HKULiver_20wk_NormalLiver_LeftLateral_Mice01_S...,0.608886,-0.536098,-0.252199,-1.521416,1.106535,-0.306672,-0.614879,-1.162273,0.056945,-0.174142,-0.073177,-0.961616,-0.105630,-0.724925,0
4,HKULiver_20wk_NormalLiver_LeftLateral_Mice01_S...,-0.060447,-0.849163,-0.485757,-1.521416,1.478627,-0.681653,-0.838816,-1.162273,-0.749510,-0.781633,-0.664349,-1.232502,0.088175,-0.724925,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446368,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,0.118477,-2.816098,-0.135375,-1.481990,-1.583552,-1.363534,-2.903040,-0.577605,0.070234,1.720414,1.008232,-2.052740,-1.786066,-0.651040,2
446369,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,0.362748,-2.816098,-0.135375,-1.481990,-1.715775,-1.289841,-2.903040,-0.577605,-0.037978,1.342527,1.687290,-0.479456,-1.786066,-0.651040,2
446370,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,0.146787,-2.816098,-0.135375,-0.401833,-2.963623,-1.200898,-2.903040,1.367008,0.222042,1.402804,-0.747119,-0.614254,-1.786066,-0.651040,2
446371,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,-0.037829,-2.816098,-0.135375,-1.481990,-2.963623,-1.553132,-2.903040,-0.577605,-0.931716,1.468600,-0.747119,-0.985103,-1.786066,-0.651040,2
446372,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,-0.026180,-2.816098,-0.135375,-1.481990,-1.662700,-1.629699,-2.903040,-0.577605,-0.051485,1.310582,-0.747119,-0.994451,-1.786066,-0.651040,2

In [8]:
## input training set ##
## calculate weight ## 0: 198536, 1: 171018, 2: 9369
Yy_train = trainDEFSDf["type"]  # 0.7494; 0.8700; 1.9369
sampleW = []
for w in Yy_train:
    if w == 0:
        sampleW.append(0.7494)
    elif w == 1:
        sampleW.append(0.8700) 
    elif w == 2:
        sampleW.append(1.9369)

In [9]:
ext1011DEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\df1011prog_ext_raMSIn4nonInDI_norm.csv")
ext2021DEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\df2021prog_ext_raMSIn4nonInDI_norm.csv")
ext3031DEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\df3031prog_ext_raMSIn4nonInDI_norm.csv")

In [10]:
for i in range(len(ext3031DEFSDf)):
    if ext3031DEFSDf.iloc[i]["type"] == 1:
        ext3031DEFSDf.at[i, "type"] = 2

In [11]:
ext3031DEFSDf

,pixel_id,250.1448,303.2329,295.2278,480.3099,215.0326,255.233,327.233,619.2894,865.5025,311.1688,269.2486,738.5062,435.2964,514.2848,type
0,HKULiver_Post29wk_HCCAMCLiver_Left_Mice02_Slid...,0.911366,-2.998719,-0.096146,-1.571867,-1.531460,-1.720199,-3.197503,-0.578867,-1.463248,2.377582,-0.566361,-2.288127,-1.560774,-0.689265,0
1,HKULiver_Post29wk_HCCAMCLiver_Left_Mice02_Slid...,1.260290,-2.998719,-0.096146,-1.571867,-3.768285,-1.871007,-3.197503,-0.578867,-0.208583,2.674299,-0.566361,-2.288127,-1.560774,-0.689265,0
2,HKULiver_Post29wk_HCCAMCLiver_Left_Mice02_Slid...,0.965544,-2.998719,-0.096146,-1.571867,-1.068431,-1.628374,-3.197503,-0.578867,-0.230461,3.143498,-0.566361,-2.288127,-1.560774,-0.689265,0
3,HKULiver_Post29wk_HCCAMCLiver_Left_Mice02_Slid...,2.195952,-2.998719,-0.096146,-1.571867,-1.213101,-1.488058,-3.197503,-0.578867,-1.463248,3.485103,-0.566361,-0.957272,-1.560774,-0.689265,0
4,HKULiver_Post29wk_HCCAMCLiver_Left_Mice02_Slid...,1.243587,-2.998719,-0.096146,-1.571867,-1.787420,-1.634959,-3.197503,-0.578867,-1.463248,2.271046,-0.566361,-1.363213,-1.560774,-0.689265,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54927,HKULiver_Post29wk_HCCLiver_Left_Mice10_Slide2_...,-2.629649,-1.740471,-0.096146,-0.246896,-3.768285,-0.873147,-1.878365,-0.578867,0.251935,0.465823,-0.566361,-0.890830,-1.560774,-0.689265,2
54928,HKULiver_Post29wk_HCCLiver_Left_Mice10_Slide2_...,-2.629649,-1.743273,-0.096146,0.239207,-3.768285,-0.921467,-1.931639,-0.578867,0.591626,0.027510,-0.566361,-0.820254,-1.560774,-0.689265,2
54929,HKULiver_Post29wk_HCCLiver_Left_Mice10_Slide2_...,-2.629649,-2.022803,-0.096146,-1.571867,-3.768285,-0.956720,-2.151214,-0.578867,0.611502,0.041157,-0.566361,-0.933945,-1.560774,-0.689265,2
54930,HKULiver_Post29wk_HCCLiver_Left_Mice10_Slide2_...,-2.629649,-2.013755,-0.096146,-1.571867,-3.768285,-1.166509,-2.220736,-0.578867,-0.062801,0.065515,-0.566361,-0.924484,-1.560774,-0.689265,2
54931,HKULiver_Post29wk_HCCLiver_Left_Mice10_Slide2_...,-2.629649,-1.580098,-0.096146,-1.571867,-3.768285,-1.139849,-1.640301,-0.578867,0.407969,0.451979,-0.566361,-1.164177,-1.560774,-0.689265,2

In [12]:
extDEFSDf = pd.concat([ext1011DEFSDf, ext2021DEFSDf, ext3031DEFSDf]).reset_index().drop(columns=["index"])

In [13]:
extDEFSDf

,pixel_id,250.1448,303.2329,295.2278,480.3099,215.0326,255.233,327.233,619.2894,865.5025,311.1688,269.2486,738.5062,435.2964,514.2848,type
0,HKULiver_20wk_NormalLiver_LeftLateral_Mice02_S...,-0.792792,-1.545787,-1.450450,-1.606074,-0.170337,-0.976438,-1.608870,-1.316538,-0.625435,1.209087,-0.930842,-1.569077,-0.120102,-1.070791,0
1,HKULiver_20wk_NormalLiver_LeftLateral_Mice02_S...,-0.672923,-1.660769,-1.450450,-1.606074,-0.128988,-1.029805,-1.715422,-1.316538,-0.596079,1.174096,-0.833795,-1.311777,-0.276215,-1.070791,0
2,HKULiver_20wk_NormalLiver_LeftLateral_Mice02_S...,-0.397883,-1.528402,-1.450450,-1.606074,0.069130,-1.003048,-1.463637,-1.316538,-0.389142,0.654054,-0.857621,-1.807367,-0.199078,-1.070791,0
3,HKULiver_20wk_NormalLiver_LeftLateral_Mice02_S...,-0.923908,-1.356627,-0.453357,-1.606074,0.772651,-1.027103,-1.283791,-1.316538,-0.955653,1.014284,-0.922428,-1.496370,0.196161,0.006335,0
4,HKULiver_20wk_NormalLiver_LeftLateral_Mice02_S...,-0.873566,-1.145180,-0.432729,-1.606074,0.918598,-0.642264,-1.066356,-1.316538,-0.534078,1.008437,-0.271217,-1.320052,0.374161,-1.070791,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147713,HKULiver_Post29wk_HCCLiver_Left_Mice10_Slide2_...,-2.629649,-1.740471,-0.096146,-0.246896,-3.768285,-0.873147,-1.878365,-0.578867,0.251935,0.465823,-0.566361,-0.890830,-1.560774,-0.689265,2
147714,HKULiver_Post29wk_HCCLiver_Left_Mice10_Slide2_...,-2.629649,-1.743273,-0.096146,0.239207,-3.768285,-0.921467,-1.931639,-0.578867,0.591626,0.027510,-0.566361,-0.820254,-1.560774,-0.689265,2
147715,HKULiver_Post29wk_HCCLiver_Left_Mice10_Slide2_...,-2.629649,-2.022803,-0.096146,-1.571867,-3.768285,-0.956720,-2.151214,-0.578867,0.611502,0.041157,-0.566361,-0.933945,-1.560774,-0.689265,2
147716,HKULiver_Post29wk_HCCLiver_Left_Mice10_Slide2_...,-2.629649,-2.013755,-0.096146,-1.571867,-3.768285,-1.166509,-2.220736,-0.578867,-0.062801,0.065515,-0.566361,-0.924484,-1.560774,-0.689265,2
147717,HKULiver_Post29wk_HCCLiver_Left_Mice10_Slide2_...,-2.629649,-1.580098,-0.096146,-1.571867,-3.768285,-1.139849,-1.640301,-0.578867,0.407969,0.451979,-0.566361,-1.164177,-1.560774,-0.689265,2

In [14]:
## input ext val set ##
## calculate weight ## 0: 62762, 1: 57028, 2: 27928
Yy_ext = extDEFSDf["type"]  # 0.7845; 0.8634; 1.7631
sampleExtW = []
for w in Yy_ext:
    if w == 0:
        sampleExtW.append(0.7845)
    elif w == 1:
        sampleExtW.append(0.8634) 
    elif w == 2:
        sampleExtW.append(1.7631)

In [15]:
ingested1011DEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\df1011prog_ingested_raMSIn4nonInDI_norm.csv")
ingested2021DEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\df2021prog_ingested_raMSIn4nonInDI_norm.csv")
ingested3031DEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\df3031prog_ingested_raMSIn4nonInDI_norm.csv")

In [16]:
for i in range(len(ingested3031DEFSDf)):
    if ingested3031DEFSDf.iloc[i]["type"] == 1:
        ingested3031DEFSDf.at[i, "type"] = 2

In [17]:
ingested3031DEFSDf

,pixel_id,250.1448,303.2329,295.2278,480.3099,215.0326,255.233,327.233,619.2894,865.5025,311.1688,269.2486,738.5062,435.2964,514.2848,type
0,HKULiver_Post29wk_HCCAMCLiver_Left_Mice01_Slid...,1.885878,-2.83714,-0.126203,-1.502857,-0.815337,-1.775884,-2.94198,-0.577411,-1.006439,1.904505,1.885464,-2.106791,-1.715041,-0.655783,0
1,HKULiver_Post29wk_HCCAMCLiver_Left_Mice01_Slid...,2.186930,-2.83714,-0.126203,-1.502857,-0.455372,-1.537501,-2.94198,-0.577411,-1.006439,2.295837,1.099228,-2.106791,-1.715041,-0.655783,0
2,HKULiver_Post29wk_HCCAMCLiver_Left_Mice01_Slid...,2.594850,-2.83714,-0.126203,-1.502857,-0.987934,-1.491759,-2.94198,-0.577411,-1.006439,2.143993,-0.698396,-1.290946,-1.715041,-0.655783,0
3,HKULiver_Post29wk_HCCAMCLiver_Left_Mice01_Slid...,3.128459,-2.83714,-0.126203,-1.502857,-1.322572,-1.555705,-2.94198,-0.577411,-1.006439,1.996865,1.416246,-1.338445,-1.715041,-0.655783,0
4,HKULiver_Post29wk_HCCAMCLiver_Left_Mice01_Slid...,2.136205,-2.83714,-0.126203,-1.502857,-0.704245,-1.579560,-2.94198,-0.577411,-1.006439,2.161341,-0.698396,-1.322628,-1.715041,-0.655783,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211156,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,0.218772,-2.83714,-0.126203,-1.502857,-1.610508,-1.295323,-2.94198,-0.577411,0.089465,1.876669,1.121927,-2.106791,-1.715041,-0.655783,2
211157,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,0.464804,-2.83714,-0.126203,-1.502857,-1.750918,-1.221760,-2.94198,-0.577411,-0.028894,1.478842,1.826120,-0.491414,-1.715041,-0.655783,2
211158,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,0.247286,-2.83714,-0.126203,-0.400831,-3.076037,-1.132973,-2.94198,1.407438,0.255508,1.542299,-0.698396,-0.629819,-1.715041,-0.655783,2
211159,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,0.061340,-2.83714,-0.126203,-1.502857,-3.076037,-1.484589,-2.94198,-0.577411,-1.006439,1.611568,-0.698396,-1.010590,-1.715041,-0.655783,2
211160,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,0.073073,-2.83714,-0.126203,-1.502857,-1.694556,-1.561021,-2.94198,-0.577411,-0.043668,1.445210,-0.698396,-1.020188,-1.715041,-0.655783,2

In [18]:
ingestedDEFSDf = pd.concat([ingested1011DEFSDf, ingested2021DEFSDf, ingested3031DEFSDf]).reset_index().drop(columns=["index"])

In [19]:
ingestedDEFSDf

,pixel_id,250.1448,303.2329,295.2278,480.3099,215.0326,255.233,327.233,619.2894,865.5025,311.1688,269.2486,738.5062,435.2964,514.2848,type
0,HKULiver_20wk_NormalLiver_LeftLateral_Mice01_S...,0.048191,-1.139295,-0.517735,-1.542194,-0.920189,-0.570647,-1.178280,-1.199995,-0.376893,-0.173500,-0.317424,-1.334300,-0.217680,-0.808310,0
1,HKULiver_20wk_NormalLiver_LeftLateral_Mice01_S...,0.771991,-0.822421,-0.533879,-1.542194,-0.077502,-0.096774,-0.822446,-1.199995,0.479645,-0.078760,0.163340,-0.638977,0.476771,0.476185,0
2,HKULiver_20wk_NormalLiver_LeftLateral_Mice01_S...,0.822788,-0.494654,-0.073712,-1.542194,0.166100,-0.009148,-0.614079,-1.199995,0.385524,-0.154777,-0.077273,-0.555298,0.555829,-0.808310,0
3,HKULiver_20wk_NormalLiver_LeftLateral_Mice01_S...,0.550462,-0.556386,-0.198104,-1.542194,1.053853,-0.339252,-0.640592,-1.199995,0.039679,-0.149079,-0.101925,-1.018479,-0.149633,-0.808310,0
4,HKULiver_20wk_NormalLiver_LeftLateral_Mice01_S...,-0.113407,-0.884049,-0.436804,-1.542194,1.415406,-0.720015,-0.875503,-1.199995,-0.790665,-0.805739,-0.695747,-1.286483,0.050183,-0.808310,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594086,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,0.218772,-2.837140,-0.126203,-1.502857,-1.610508,-1.295323,-2.941980,-0.577411,0.089465,1.876669,1.121927,-2.106791,-1.715041,-0.655783,2
594087,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,0.464804,-2.837140,-0.126203,-1.502857,-1.750918,-1.221760,-2.941980,-0.577411,-0.028894,1.478842,1.826120,-0.491414,-1.715041,-0.655783,2
594088,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,0.247286,-2.837140,-0.126203,-0.400831,-3.076037,-1.132973,-2.941980,1.407438,0.255508,1.542299,-0.698396,-0.629819,-1.715041,-0.655783,2
594089,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,0.061340,-2.837140,-0.126203,-1.502857,-3.076037,-1.484589,-2.941980,-0.577411,-1.006439,1.611568,-0.698396,-1.010590,-1.715041,-0.655783,2
594090,HKULiver_Post29wk_HCCLiver_Left_Mice12_Slide1_...,0.073073,-2.837140,-0.126203,-1.502857,-1.694556,-1.561021,-2.941980,-0.577411,-0.043668,1.445210,-0.698396,-1.020188,-1.715041,-0.655783,2

In [20]:
## input ingested set ##
## calculate weight ## 0: 261298, 1: 228046, 2: 104747
Yy_ingested = ingestedDEFSDf["type"]  # 0.7579; 0.8684; 1.8906
sampleIngestedW = []
for w in Yy_ingested:
    if w == 0:
        sampleIngestedW.append(0.7579)
    elif w == 1:
        sampleIngestedW.append(0.8684)
    elif w == 2:
        sampleIngestedW.append(1.8906)

In [21]:
fna1011DEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\df1011prog_FNA_raMSIn4nonInDI_norm.csv")
fna2021DEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\df2021prog_FNA_raMSIn4nonInDI_norm.csv")
fna3031DEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\df3031prog_FNA_raMSIn4nonInDI_norm.csv")

In [22]:
for i in range(len(fna3031DEFSDf)):
    if fna3031DEFSDf.iloc[i]["type"] == 1:
        fna3031DEFSDf.at[i, "type"] = 2

In [23]:
fna3031DEFSDf

,pixel_id,250.1448,303.2329,295.2278,480.3099,215.0326,255.233,327.233,619.2894,865.5025,311.1688,269.2486,738.5062,435.2964,514.2848,type
0,HKULiver_Post29wk_HCCAMCLiver_FNA_Mice01_Slide...,0.536771,-3.135934,0.220866,-0.644612,1.125029,-1.415481,-3.000180,-0.1819,-0.945667,3.550437,-1.258848,-2.361358,-1.126855,2.248451,0
1,HKULiver_Post29wk_HCCAMCLiver_FNA_Mice01_Slide...,1.464512,-2.278751,0.815011,-0.644612,1.087153,-0.773135,-2.258729,-0.1819,-0.945667,-0.178049,0.262033,0.034942,0.184904,1.667605,0
2,HKULiver_Post29wk_HCCAMCLiver_FNA_Mice01_Slide...,1.779394,-2.407469,0.423792,-0.644612,1.113149,-1.018557,-3.000180,-0.1819,-0.945667,-0.178049,0.474462,-2.361358,0.364819,2.263980,0
3,HKULiver_Post29wk_HCCAMCLiver_FNA_Mice01_Slide...,6.401994,-1.983634,5.321370,-0.644612,2.007743,4.621564,-1.964312,-0.1819,-0.945667,-0.178049,4.155306,1.162345,2.370323,5.608092,0
4,HKULiver_Post29wk_HCCAMCLiver_FNA_Mice01_Slide...,6.728735,-1.872587,5.924446,-0.644612,2.353988,4.892140,-2.123702,-0.1819,-0.945667,-0.178049,3.761935,1.461837,1.858677,7.106333,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88696,HKULiver_Post29wk_HCCLiver_FNA_Mice11_Slide2_6...,4.432895,-2.205354,0.920637,-0.644612,-1.017987,0.490308,-3.000180,-0.1819,-0.945667,-0.178049,1.913466,-2.361358,-1.126855,-0.518481,2
88697,HKULiver_Post29wk_HCCLiver_FNA_Mice11_Slide2_6...,5.707259,-2.159328,1.314414,-0.644612,-1.017987,0.583926,-3.000180,-0.1819,-0.945667,-0.178049,1.919197,-2.361358,-1.126855,-0.518481,2
88698,HKULiver_Post29wk_HCCLiver_FNA_Mice11_Slide2_6...,5.764262,-3.135934,1.123965,-0.644612,-1.017987,0.831786,-2.328141,-0.1819,-0.945667,-0.178049,4.789774,-2.361358,-1.126855,-0.518481,2
88699,HKULiver_Post29wk_HCCLiver_FNA_Mice11_Slide2_6...,5.667844,-2.030095,1.413237,-0.644612,-1.017987,0.972824,-3.000180,-0.1819,-0.945667,-0.178049,2.363939,-2.361358,-1.126855,-0.518481,2
88700,HKULiver_Post29wk_HCCLiver_FNA_Mice11_Slide2_6...,4.985276,-2.274363,0.592437,-0.644612,-1.017987,0.674739,-2.219891,-0.1819,-0.945667,-0.178049,1.667634,-2.361358,-1.126855,-0.518481,2

In [24]:
fnaDEFSDf = pd.concat([fna1011DEFSDf, fna2021DEFSDf, fna3031DEFSDf]).reset_index().drop(columns=["index"])

In [25]:
fnaDEFSDf

,pixel_id,250.1448,303.2329,295.2278,480.3099,215.0326,255.233,327.233,619.2894,865.5025,311.1688,269.2486,738.5062,435.2964,514.2848,type
0,HKULiver_Post02wk_FibrosisAMCLiver_FNA_Mice01_...,5.176380,-2.931897,-1.827983,-0.900706,-1.544948,-2.961026,-2.703721,-0.339503,-1.071456,6.557732,-1.607610,1.218694,-2.265912,-0.179738,0
1,HKULiver_Post02wk_FibrosisAMCLiver_FNA_Mice01_...,5.752168,-2.270778,-1.827983,1.048574,-1.544948,-2.671156,-2.703721,-0.339503,-1.071456,6.133702,-1.607610,1.350590,-2.265912,-0.179738,0
2,HKULiver_Post02wk_FibrosisAMCLiver_FNA_Mice01_...,5.320968,-2.073123,-1.827983,0.735997,-1.544948,-2.324972,-2.101316,-0.339503,1.199499,6.021397,-1.607610,0.796538,-2.265912,-0.179738,0
3,HKULiver_Post02wk_FibrosisAMCLiver_FNA_Mice01_...,6.913170,-2.355549,-1.827983,-0.900706,-1.544948,-2.563419,-2.194686,-0.339503,-1.071456,7.724311,-1.607610,0.307795,-2.265912,-0.179738,0
4,HKULiver_Post02wk_FibrosisAMCLiver_FNA_Mice01_...,6.742121,-2.300661,-1.827983,0.944493,-1.544948,-2.555561,-2.181713,-0.339503,0.959884,6.817430,-0.245240,1.157051,-2.265912,-0.179738,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276433,HKULiver_Post29wk_HCCLiver_FNA_Mice11_Slide2_6...,4.432895,-2.205354,0.920637,-0.644612,-1.017987,0.490308,-3.000180,-0.181900,-0.945667,-0.178049,1.913466,-2.361358,-1.126855,-0.518481,2
276434,HKULiver_Post29wk_HCCLiver_FNA_Mice11_Slide2_6...,5.707259,-2.159328,1.314414,-0.644612,-1.017987,0.583926,-3.000180,-0.181900,-0.945667,-0.178049,1.919197,-2.361358,-1.126855,-0.518481,2
276435,HKULiver_Post29wk_HCCLiver_FNA_Mice11_Slide2_6...,5.764262,-3.135934,1.123965,-0.644612,-1.017987,0.831786,-2.328141,-0.181900,-0.945667,-0.178049,4.789774,-2.361358,-1.126855,-0.518481,2
276436,HKULiver_Post29wk_HCCLiver_FNA_Mice11_Slide2_6...,5.667844,-2.030095,1.413237,-0.644612,-1.017987,0.972824,-3.000180,-0.181900,-0.945667,-0.178049,2.363939,-2.361358,-1.126855,-0.518481,2
276437,HKULiver_Post29wk_HCCLiver_FNA_Mice11_Slide2_6...,4.985276,-2.274363,0.592437,-0.644612,-1.017987,0.674739,-2.219891,-0.181900,-0.945667,-0.178049,1.667634,-2.361358,-1.126855,-0.518481,2

In [26]:
## input FNA set ##
## calculate weight ##  0: 138676, 1: 93601, 2: 44161
Yy_FNA = fnaDEFSDf["type"]  # 0.6645; 0.9845; 2.0866
sampleFNAW = []
for w in Yy_FNA:
    if w == 0:
        sampleFNAW.append(0.6645)
    elif w == 1:
        sampleFNAW.append(0.9845)
    elif w == 2:
        sampleFNAW.append(2.0866)

In [27]:
di1011DEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\df1011prog_nonInDI_raMSIn4nonInDI_norm.csv")
di2021DEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\df2021prog_nonInDI_raMSIn4nonInDI_norm.csv")
di3031DEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\df3031prog_nonInDI_raMSIn4nonInDI_norm.csv")

In [28]:
for i in range(len(di3031DEFSDf)):
    if di3031DEFSDf.iloc[i]["type"] == 1:
        di3031DEFSDf.at[i, "type"] = 2

In [29]:
di3031DEFSDf

,pixel_id,250.1448,303.2329,295.2278,480.3099,215.0326,255.233,327.233,619.2894,865.5025,311.1688,269.2486,738.5062,435.2964,514.2848,type
0,HKULiver_Post29wk_HCCAMCLiver_DirectIn_MiceNL_...,-0.557684,0.142556,0.297338,-0.053237,-0.734010,0.249990,0.347424,0.529488,0.938385,0.532071,-0.097725,0.513433,0.532605,3.574904,0
1,HKULiver_Post29wk_HCCAMCLiver_DirectIn_MiceNL_...,-0.557684,0.249627,0.619464,-0.056646,-0.734010,0.431894,0.227797,0.145652,0.419814,0.439644,-0.003330,0.146027,0.906042,3.572686,0
2,HKULiver_Post29wk_HCCAMCLiver_DirectIn_MiceNL_...,-0.557684,0.361833,0.380672,-0.031853,1.001020,0.366950,0.477531,0.321606,0.558540,0.773630,-1.048734,0.273914,-0.740738,3.837168,0
3,HKULiver_Post29wk_HCCAMCLiver_DirectIn_MiceNL_...,-0.557684,-0.013789,0.396015,-0.130905,-0.734010,0.126103,-0.156333,0.080754,0.149481,0.396571,-0.132648,-0.112103,-0.740738,3.182561,0
4,HKULiver_Post29wk_HCCAMCLiver_DirectIn_MiceNL_...,-0.557684,0.268821,0.456683,-0.061129,-0.734010,0.375838,0.321419,0.159865,0.345865,0.542241,-0.074071,0.200724,-0.740738,3.414990,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5019,HKULiver_Post29wk_HCCLiver_DirectIn_MiceHCC_S1...,-0.557684,0.012355,-0.240457,-0.141924,-0.077499,-0.063672,-0.018096,-0.022745,-0.068611,-0.356958,-0.137607,0.203561,0.120724,-0.209984,2
5020,HKULiver_Post29wk_HCCLiver_DirectIn_MiceHCC_S1...,-0.557684,-0.237721,-0.288628,-0.334284,-0.734010,-0.278786,-0.305370,-0.270958,-0.315251,-0.488794,-0.156696,-0.207569,0.364862,-0.256546,2
5021,HKULiver_Post29wk_HCCLiver_DirectIn_MiceHCC_S1...,-0.557684,-0.692516,-0.517206,-0.808702,-0.734010,-0.494143,-0.734347,-0.948077,-0.845557,-0.922313,-0.399695,-0.665621,-0.740738,-0.387695,2
5022,HKULiver_Post29wk_HCCLiver_DirectIn_MiceHCC_S1...,0.248832,0.124388,-0.287031,-0.211558,0.141614,0.043227,0.183715,-0.074593,-0.134643,-0.363600,-0.080973,0.364027,0.688160,-0.217502,2
5023,HKULiver_Post29wk_HCCLiver_DirectIn_MiceHCC_S12_,7.668868,12.651320,10.633014,10.572069,7.802149,13.208954,12.599601,11.759436,8.485218,7.935551,13.256687,14.542095,13.085687,2.504290,2

In [30]:
diDEFSDf = pd.concat([di1011DEFSDf, di2021DEFSDf, di3031DEFSDf]).reset_index().drop(columns=["index"])

In [31]:
diDEFSDf

,pixel_id,250.1448,303.2329,295.2278,480.3099,215.0326,255.233,327.233,619.2894,865.5025,311.1688,269.2486,738.5062,435.2964,514.2848,type
0,HKULiver_Post02wk_FibrosisAMCLiver_DirectIn_Mi...,-0.742517,0.817880,0.226954,0.498961,0.594555,0.369107,0.695841,1.086973,-0.500894,-0.157886,-0.131016,0.711575,1.101213,-0.927898,0
1,HKULiver_Post02wk_FibrosisAMCLiver_DirectIn_Mi...,1.176867,0.129656,0.009781,0.404838,0.467349,0.086155,0.157549,0.615962,-0.145756,-0.438767,0.623927,0.489570,0.379070,-0.953905,0
2,HKULiver_Post02wk_FibrosisAMCLiver_DirectIn_Mi...,2.326685,-0.065915,0.072635,0.355665,0.624461,0.130895,-0.030179,0.569902,-0.507921,-0.586111,0.725327,0.143068,0.622613,-1.007904,0
3,HKULiver_Post02wk_FibrosisAMCLiver_DirectIn_Mi...,2.553732,-0.125355,0.639258,-0.069092,0.350930,0.286873,-0.289721,-0.281501,-0.669904,-1.025493,0.392700,-0.503154,0.710666,-1.064603,0
4,HKULiver_Post02wk_FibrosisAMCLiver_DirectIn_Mi...,2.124389,0.600088,0.176693,0.461104,0.020849,0.340478,0.358510,0.390346,-0.435642,-0.491734,0.289191,0.095113,0.419554,-1.020799,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12452,HKULiver_Post29wk_HCCLiver_DirectIn_MiceHCC_S1...,-0.557684,0.012355,-0.240457,-0.141924,-0.077499,-0.063672,-0.018096,-0.022745,-0.068611,-0.356958,-0.137607,0.203561,0.120724,-0.209984,2
12453,HKULiver_Post29wk_HCCLiver_DirectIn_MiceHCC_S1...,-0.557684,-0.237721,-0.288628,-0.334284,-0.734010,-0.278786,-0.305370,-0.270958,-0.315251,-0.488794,-0.156696,-0.207569,0.364862,-0.256546,2
12454,HKULiver_Post29wk_HCCLiver_DirectIn_MiceHCC_S1...,-0.557684,-0.692516,-0.517206,-0.808702,-0.734010,-0.494143,-0.734347,-0.948077,-0.845557,-0.922313,-0.399695,-0.665621,-0.740738,-0.387695,2
12455,HKULiver_Post29wk_HCCLiver_DirectIn_MiceHCC_S1...,0.248832,0.124388,-0.287031,-0.211558,0.141614,0.043227,0.183715,-0.074593,-0.134643,-0.363600,-0.080973,0.364027,0.688160,-0.217502,2
12456,HKULiver_Post29wk_HCCLiver_DirectIn_MiceHCC_S12_,7.668868,12.651320,10.633014,10.572069,7.802149,13.208954,12.599601,11.759436,8.485218,7.935551,13.256687,14.542095,13.085687,2.504290,2

In [32]:
## input DirectIn set ##
## calculate weight ## 0: 6209, 1: 3724, 2: 2524
Yy_DI = diDEFSDf["type"]  # 0.6688; 1.1150; 1.6451
sampleDiW = []
for w in Yy_DI:
    if w == 0:
        sampleDiW.append(0.6688)
    elif w == 1:
        sampleDiW.append(1.1150)
    elif w == 2:
        sampleDiW.append(1.6451)

In [33]:
di1011PMDEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\df1011prog_nonInPMDI_raMSIn4nonInDI_norm.csv")

In [34]:
di1011PMDEFSDf

,pixel_id,250.1448,303.2329,295.2278,480.3099,215.0326,255.233,327.233,619.2894,865.5025,311.1688,269.2486,738.5062,435.2964,514.2848,type
0,HKBULiver_Halfyear_FibrosisAMCLiver_DirectIn_M...,-0.36933,0.088734,0.452591,0.624357,0.744042,0.345283,0.982864,0.291689,1.040174,0.290187,-0.094526,0.321747,0.085217,-0.445423,0
1,HKBULiver_Halfyear_FibrosisAMCLiver_DirectIn_M...,-0.36933,-0.201833,0.604872,0.460051,-0.810637,0.452955,0.308910,0.058328,0.686840,0.182935,0.328750,0.392576,-0.114069,-0.484110,0
2,HKBULiver_Halfyear_FibrosisAMCLiver_DirectIn_M...,-0.36933,-0.164687,0.249824,0.892365,0.782306,0.048529,0.107290,-0.656984,0.663825,-0.113763,0.823456,0.112642,-1.114433,-0.465705,0
3,HKBULiver_Halfyear_FibrosisAMCLiver_DirectIn_M...,-0.36933,-0.097753,0.731184,0.541603,-0.810637,0.430904,0.704984,-0.434250,1.963588,-0.037164,0.561729,1.260449,0.465858,-0.494882,0
4,HKBULiver_Halfyear_FibrosisAMCLiver_DirectIn_M...,-0.36933,-0.602424,0.280637,-0.087438,0.419113,-0.318601,-0.163125,-0.861845,-0.297223,-0.306744,-0.131589,-0.793509,-0.441613,-0.510262,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3359,HKBULiver_Halfyear_FibrosisLiver_DirectIn_Mice...,-0.36933,0.200524,-0.647980,0.233060,-0.810637,0.765507,0.191102,-0.075249,-0.218766,1.475244,0.340192,-0.500204,0.509061,-0.627430,1
3360,HKBULiver_Halfyear_FibrosisLiver_DirectIn_Mice...,-0.36933,0.344717,-0.208700,0.423365,-0.810637,1.252085,0.132593,0.278179,-0.036554,1.534465,1.317275,-0.826349,-0.141638,-0.623744,1
3361,HKBULiver_Halfyear_FibrosisLiver_DirectIn_Mice...,-0.36933,0.349257,-0.228705,0.880851,0.195907,1.383750,0.084254,0.416100,0.537164,1.555862,0.725883,0.813694,0.337516,-0.652096,1
3362,HKBULiver_Halfyear_FibrosisLiver_DirectIn_Mice...,-0.36933,-0.221511,-0.812250,-0.337346,-0.810637,0.318545,-0.159116,0.150794,-0.189410,1.157331,-0.444499,-0.251843,-0.059958,-0.658126,1
3363,HKBULiver_Halfyear_FibrosisLiver_DirectIn_Mice...,-0.36933,0.255189,0.029164,0.727502,-0.810637,1.681617,-0.078589,-0.025528,0.698174,1.336357,1.571974,1.320346,-0.884968,-0.647519,1

In [35]:
## input PM DirectIn set ##
## calculate weight ## 0: 1673, 1: 1691, 2: 0
Yy_PMDI = di1011PMDEFSDf["type"]  # 1.0054; 0.9947
samplePMDiW = []
for w in Yy_PMDI:
    if w == 0:
        samplePMDiW.append(1.0054)
    elif w == 1:
        samplePMDiW.append(0.9947)

In [36]:
di3031OldDEFSDf = pd.read_csv(r"I:\\4_output_FIBproj\\dfOld3031prog_nonInDI_raMSIn4nonInDI_norm.csv")

In [37]:
for i in range(len(di3031OldDEFSDf)):
    if di3031OldDEFSDf.iloc[i]["type"] == 1:
        di3031OldDEFSDf.at[i, "type"] = 2

In [38]:
di3031OldDEFSDf

,pixel_id,250.1448,303.2329,295.2278,480.3099,215.0326,255.233,327.233,619.2894,865.5025,311.1688,269.2486,738.5062,435.2964,514.2848,type
0,HKULiver_Post29wk_HCCAMCLiver_DirectIn_MiceNL_...,2.441502,-0.531504,0.028643,0.358034,0.253639,0.091023,-0.648194,-0.123745,-0.471098,0.041542,0.988487,0.484413,0.606944,0.274395,0
1,HKULiver_Post29wk_HCCAMCLiver_DirectIn_MiceNL_...,3.047292,-0.084209,0.009341,1.047140,1.078766,0.550410,-0.390722,0.321979,0.356093,0.711203,1.086604,1.002423,0.701739,0.748943,0
2,HKULiver_Post29wk_HCCAMCLiver_DirectIn_MiceNL_...,2.430234,-0.103293,-0.514353,0.252168,0.224697,0.119352,-0.573842,0.060066,-0.317467,0.261847,0.932337,0.226970,0.370467,0.427222,0
3,HKULiver_Post29wk_HCCAMCLiver_DirectIn_MiceNL_...,2.876938,0.150532,0.424699,0.535658,0.391985,0.960652,-0.462062,0.231343,-0.028972,0.643012,1.633615,0.846705,0.930685,0.679182,0
4,HKULiver_Post29wk_HCCAMCLiver_DirectIn_MiceNL_...,3.372216,0.645849,0.592759,1.002038,0.943542,1.429073,0.208089,0.861039,0.689637,1.052209,1.646028,1.850201,0.986375,1.107675,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6052,HKULiver_Post29wk_HCCLiver_DirectIn_MiceHCC_S1...,-0.466952,-0.927841,-0.289144,0.668465,0.790429,-0.468662,-0.737929,0.555552,-0.024752,-0.016246,-1.455099,0.182180,0.709641,1.227471,2
6053,HKULiver_Post29wk_HCCLiver_DirectIn_MiceHCC_S1...,-0.131893,-2.297799,-2.210047,-2.191815,-1.862881,-2.495026,-1.781421,-2.559035,-1.927167,-2.486192,-1.514339,-2.197111,-1.339711,-1.894160,2
6054,HKULiver_Post29wk_HCCLiver_DirectIn_MiceHCC_S1...,-0.466952,-1.358241,-0.358331,-0.947437,0.010830,-0.883431,-1.147980,-1.219617,-0.613528,-1.255696,-0.258525,-0.664897,-0.190021,0.688127,2
6055,HKULiver_Post29wk_HCCLiver_DirectIn_MiceHCC_S1...,-0.053194,-1.276659,-0.797119,-0.893108,0.415314,-0.953334,-0.974419,-0.917053,-0.586729,-1.032863,-0.696885,-0.540272,-0.340627,-0.135626,2
6056,HKULiver_Post29wk_HCCLiver_DirectIn_MiceHCC_S1...,-0.134644,-2.836885,-2.827878,-2.647931,-1.862881,-2.792980,-2.521951,-2.559035,-1.927167,-2.977298,-2.926079,-2.197111,-1.339711,-2.348972,2

In [39]:
## input Old3031 DirectIn set ##
## calculate weight ## 0: 3027, 1: 0, 2: 3030
Yy_3031OldDI = di3031OldDEFSDf["type"]  # 1.0005; 0.9995
sample3031OldDiW = []
for w in Yy_3031OldDI:
    if w == 0:
        sample3031OldDiW.append(1.0005)
    elif w == 2:
        sample3031OldDiW.append(0.9995)

In [40]:
## define functions for performace evaluation ##

# Average score
def avgScore(arrAcc, cv):
    sumAcc = 0
    for acc in arrAcc:
        sumAcc += acc
    return sumAcc / cv

In [ ]:
trainDEFSDf[trainDEFSDf.columns[1:-1]]

In [78]:
## define a function for Gradient Boost ##
def optimXGBoostClass(inputDB_train, inputDB_ext, inputDB_ingested, inputDB_PMdi, inputDB_OldDi):
    #lr_r = [4, 2, 1]  #3
    #lr_r = [4, 6, 8]  # 3
    #lr_r = [2.5, 2.6, 2.7, 2.8, 2.9, 3, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4, 
    #        4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5, 5.1, 5.2, 5.3, 5.4, 5.5]  # 31
    lr_r = [2.52, 2.54, 2.56, 2.58, 2.6, 2.62, 2.64, 2.66, 2.68, 2.7, 2.72, 2.74, 2.76, 2.78, 2.8, 
            2.82, 2.84, 2.86, 2.88, 2.9]  # 20
    #lr_r = [4.6, 4.61, 4.62, 4.63, 4.64, 4.65, 4.66, 4.67, 4.68, 4.69, 4.7, 4.71, 4.72, 4.73, 4.74, 4.75, 4.76, 4.77, 4.78, 4.79, 4.8]  # 21
    #cols_r = [0.55, 0.65, 0.75, 0.85, 0.95]  # 4
    #cols_r = [0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1]  # 12
    #cols_r = [0.8]  # 12
    cols_r = [0.72, 0.74, 0.76, 0.78, 0.8, 0.82, 0.84, 0.86, 0.88]  # 9
    #depth_r = [4, 5, 6]  # 3
    #depth_r = [4, 5]  # 2
    depth_r = [4]  # 1
    #subs_r = [0.45, 0.55, 0.65, 0.75, 0.85, 0.95]  # 12
    #subs_r = [0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1]  # 12
    #subs_r = [0.425, 0.45, 0.475, 0.5, 0.525, 0.55, 0.575]  # 7
    subs_r = [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5, 0.51, 0.52, 0.53, 0.54, 0.55]  # 15
    #tree_r = [32, 48, 64]  # 3
    tree_r = [8, 16, 32]  # 3
    #tree_r = [150, 200]  # 2
    #tree_r = [200, 300]  # 2
    #tree_r = [25, 50, 75, 100, 200, 300, 500]  # 7
    #est_r = [10] # 1
    #est_r = [2, 8] # 2
    est_r = [2] # 1
    #est_r = [96, 128] # 2#
    #est_r = [2, 8, 16, 32, 64, 96] # 6

    rs = 42
    z = np.zeros(49)
    itr = 1

    M_train = inputDB_train
    N_train = pd.concat([M_train, M_train.loc[M_train["type"] == 2]]).reset_index().drop(columns=["index"])
    M_val = inputDB_ext
    M_test = inputDB_ingested
    M_test2 = inputDB_PMdi
    M_ext = inputDB_OldDi

    for lr in lr_r:
        for c in cols_r:
            for d in depth_r:
                for s in subs_r:
                    for t in tree_r:
                        for est in est_r:
    
                            print("itr=", itr, ", lr=", lr, ", cols=", c, ", depth=", d, ", sub=", s, ", tree=", t, ", est=", est)
                            print("## loading in data ##")
                            Xx_train = M_train[M_train.columns[1:-1]]
                            nn_train = N_train[N_train.columns[1:-1]]
                            Xx_val = M_val[M_val.columns[1:-1]]
                            Xx_test = M_test[M_test.columns[1:-1]]
                            Xx_test2 = M_test2[M_test2.columns[1:-1]]
                            Xx_ext = M_ext[M_ext.columns[1:-1]]
                            #
                            Yy_train = M_train["type"]
                            mm_train = N_train["type"]
                            Yy_val = M_val["type"]
                            Yy_test = M_test["type"]
                            Yy_test2 = M_test2["type"]
                            Yy_ext = M_ext["type"]
                            print("## Classification ##")
                            model_xgb = xgb.XGBClassifier(
                                base_score = 0.5, 
                                booster = 'gbtree', 
                                colsample_bylevel = 1, 
                                colsample_bynode = 1, 
                                colsample_bytree = c, 
                                enable_categorical = False, 
                                eval_metric = 'auc', 
                                gamma = 0, 
                                gpu_id = -1, 
                                grow_policy = 'lossguide', 
                                importance_type = None, 
                                learning_rate = lr, 
                                max_bin = 256, 
                                max_cat_to_onehot = 4, 
                                max_delta_step = 0, 
                                max_depth = d, 
                                max_leaves = 0, 
                                min_child_weight = 1, 
                                #missing = nan, 
                                monotone_constraints = '()', 
                                n_estimators = t, 
                                n_jobs = 0, 
                                num_parallel_tree = 1, 
                                objective = 'binary:hinge', 
                                predictor = 'auto', 
                                random_state = 0, 
                                reg_alpha = 0, 
                                reg_lambda = 1, 
                                sampling_method = 'uniform', 
                                scale_pos_weight = None, 
                                subsample = s, 
                                tree_method = 'hist', 
                                use_label_encoder = False, 
                                validate_parameters = 1, 
                                verbosity = None, 
                                early_stopping_rounds = est)

                            # Training Set
                            model_xgb.fit(Xx_train, Yy_train, 
                                          eval_set=[(Xx_val, Yy_val), (Xx_test, Yy_test)])

                            fit_params = {'eval_set': [[Xx_val, Yy_val], [Xx_test, Yy_test]], 'eval_metric': }

                            importances = permutation_importance(model_xgb, Xx_test, Yy_test, n_repeats=10, random_state=42, n_jobs=-1)
                            #print(importances["importances_mean"])

                            if itr == 1:
                                z[0] = lr
                                z[1] = c
                                z[2] = d
                                z[3] = s
                                z[4] = t
                                z[5] = est
                                z[6] = f1_score(Yy_train, model_xgb.predict(Xx_train), average='weighted', sample_weight=sampleW)
                                z[7] = matthews_corrcoef(Yy_train, model_xgb.predict(Xx_train), sample_weight=sampleW)
                                z[8] = f1_score(Yy_val, model_xgb.predict(Xx_val), average='weighted', sample_weight=sampleExtW)
                                z[9] = matthews_corrcoef(Yy_val, model_xgb.predict(Xx_val), sample_weight=sampleExtW)
                                print("## No CV ##")
                                scores_XGB = cross_val_score(model_xgb, nn_train, mm_train, cv=5, scoring = "f1", fit_params = fit_params)
                                z[10] = scores_XGB.mean()
                                #print(scores_XGB.mean())
                                z[11] = f1_score(Yy_test, model_xgb.predict(Xx_test), average='weighted', sample_weight=sampleIngestedW)
                                z[12] = matthews_corrcoef(Yy_test, model_xgb.predict(Xx_test), sample_weight=sampleIngestedW)
                                z[13] = recall_score(Yy_test, model_xgb.predict(Xx_test), average='weighted', sample_weight=sampleIngestedW)
                                z[14] = f1_score(Yy_test2, model_xgb.predict(Xx_test2), average='weighted', sample_weight=samplePMDiW)
                                z[15] = matthews_corrcoef(Yy_test2, model_xgb.predict(Xx_test2), sample_weight=samplePMDiW)
                                z[16] = recall_score(Yy_test2, model_xgb.predict(Xx_test2), average='weighted', sample_weight=samplePMDiW)
                                z[17] = f1_score(Yy_ext, model_xgb.predict(Xx_ext), average='weighted', sample_weight=sample3031OldDiW)
                                z[18] = matthews_corrcoef(Yy_ext, model_xgb.predict(Xx_ext), sample_weight=sample3031OldDiW)
                                z[19] = recall_score(Yy_ext, model_xgb.predict(Xx_ext), average='weighted', sample_weight=sample3031OldDiW)
                                z[20] = rs
                                z[21] = importances["importances_mean"][0]
                                z[22] = importances["importances_mean"][1]
                                z[23] = importances["importances_mean"][2]
                                z[24] = importances["importances_mean"][3]
                                z[25] = importances["importances_mean"][4]
                                z[26] = importances["importances_mean"][5]
                                z[27] = importances["importances_mean"][6]
                                z[28] = importances["importances_mean"][7]
                                z[29] = importances["importances_mean"][8]
                                z[30] = importances["importances_mean"][9]
                                z[31] = importances["importances_mean"][10]
                                z[32] = importances["importances_mean"][11]
                                z[33] = importances["importances_mean"][12]
                                z[34] = importances["importances_mean"][13]
                                z[35] = importances["importances_std"][0]
                                z[36] = importances["importances_std"][1]
                                z[37] = importances["importances_std"][2]
                                z[38] = importances["importances_std"][3]
                                z[39] = importances["importances_std"][4]
                                z[40] = importances["importances_std"][5]
                                z[41] = importances["importances_std"][6]
                                z[42] = importances["importances_std"][7]
                                z[43] = importances["importances_std"][8]
                                z[44] = importances["importances_std"][9]
                                z[45] = importances["importances_std"][10]
                                z[46] = importances["importances_std"][11]
                                z[47] = importances["importances_std"][12]
                                z[48] = importances["importances_std"][13]
                            else:
                                itrain = f1_score(Yy_train, model_xgb.predict(Xx_train), average='weighted', sample_weight=sampleW)
                                jtrain = matthews_corrcoef(Yy_train, model_xgb.predict(Xx_train), sample_weight=sampleW)
                                ival = f1_score(Yy_val, model_xgb.predict(Xx_val), average='weighted', sample_weight=sampleExtW)
                                jval = matthews_corrcoef(Yy_val, model_xgb.predict(Xx_val), sample_weight=sampleExtW)
                                print("## No CV ##")
                                scores_XGB = cross_val_score(model_xgb, nn_train, mm_train, cv=5, scoring = "f1", fit_params = fit_params)
                                traincvtrain = scores_XGB.mean()
                                f1s = f1_score(Yy_test, model_xgb.predict(Xx_test), average='weighted', sample_weight=sampleIngestedW)
                                mccs = matthews_corrcoef(Yy_test, model_xgb.predict(Xx_test), sample_weight=sampleIngestedW)
                                rec = recall_score(Yy_test, model_xgb.predict(Xx_test), average='weighted', sample_weight=sampleIngestedW)
                                f1s2 = f1_score(Yy_test2, model_xgb.predict(Xx_test2), average='weighted', sample_weight=samplePMDiW)
                                mccs2 = matthews_corrcoef(Yy_test2, model_xgb.predict(Xx_test2), sample_weight=samplePMDiW)
                                rec2 = recall_score(Yy_test2, model_xgb.predict(Xx_test2), average='weighted', sample_weight=samplePMDiW)
                                f1s3 = f1_score(Yy_ext, model_xgb.predict(Xx_ext), average='weighted', sample_weight=sample3031OldDiW)
                                mccs3 = matthews_corrcoef(Yy_ext, model_xgb.predict(Xx_ext), sample_weight=sample3031OldDiW)
                                rec3= recall_score(Yy_ext, model_xgb.predict(Xx_ext), average='weighted', sample_weight=sample3031OldDiW)
                                im1 = importances["importances_mean"][0]
                                im2 = importances["importances_mean"][1]
                                im3 = importances["importances_mean"][2]
                                im4 = importances["importances_mean"][3]
                                im5 = importances["importances_mean"][4]
                                im6 = importances["importances_mean"][5]
                                im7 = importances["importances_mean"][6]
                                im8 = importances["importances_mean"][7]
                                im9 = importances["importances_mean"][8]
                                im10 = importances["importances_mean"][9]
                                im11 = importances["importances_mean"][10]
                                im12 = importances["importances_mean"][11]
                                im13 = importances["importances_mean"][12]
                                im14 = importances["importances_mean"][13]
                                sd1 = importances["importances_std"][0]
                                sd2 = importances["importances_std"][1]
                                sd3 = importances["importances_std"][2]
                                sd4 = importances["importances_std"][3]
                                sd5 = importances["importances_std"][4]
                                sd6 = importances["importances_std"][5]
                                sd7 = importances["importances_std"][6]
                                sd8 = importances["importances_std"][7]
                                sd9 = importances["importances_std"][8]
                                sd10 = importances["importances_std"][9]
                                sd11 = importances["importances_std"][10]
                                sd12 = importances["importances_std"][11]
                                sd13 = importances["importances_std"][12]
                                sd14 = importances["importances_std"][13]
                                tem = np.array([lr, c, d, s, t, est, itrain, jtrain, ival, jval, traincvtrain, f1s, mccs, rec, f1s2, mccs2, rec2, f1s3, mccs3, rec3, rs, im1, im2, im3, im4, im5, im6, im7, im8, im9, im10, im11, im12, im13, im14, sd1, sd2, sd3, sd4, sd5, sd6, sd7, sd8, sd9, sd10, sd11, sd12, sd13, sd14])
                                z = np.row_stack([z, tem])
                                #print(z[-1])
                            print("End of ", itr, " iterations")
                            itr += 1
    z_df = pd.DataFrame(z, columns=["lr", "cols", "depth", "subs", "tree", "est", 
                                    "f1_train", "mcc_train", "f1_fnaVal", "mcc_fnaVal", 
                                    "f1_5Ftrain", "f1_DIn", "mcc_DIn", "recall_DIn", 
                                    "f1_PMDIn", "mcc_PMDIn", "recall_PMDIn", "f1_oldDIn", "mcc_oldDIn", "recall_oldDIn", "state", 
                                    "im1", "im2", "im3", "im4", "im5", "im6", "im7", "im8", "im9", "im10", "im11", "im12", "im13", "im14", 
                                    "sd1", "sd2", "sd3", "sd4", "sd5", "sd6", "sd7", "sd8", "sd9", "sd10", "sd11", "sd12", "sd13", "sd14"])

    return z_df

In [41]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
## call Gradient Boost ##
optiSearch_df = optimXGBoostClass(trainDEFSDf, extDEFSDf, ingestedDEFSDf, di1011PMDEFSDf, di3031OldDEFSDf)

In [53]:
## save ##
optiSearch_df.to_csv(r"I:/4_output_FIBproj/4_3_Output_raMSIn/modeling/hyperparameterTuning_modelSelectionSTD_XGB1.csv")

In [83]:
## define a function for non-linear SVM ##
from sklearn.svm import SVC

def optimSVMClass(inputDB_train, inputDB_ext, inputDB_ingested, inputDB_PMdi, inputDB_OldDi):
    
    #C_r = [100, 200, 300, 400, 500]
    C_r = [1000, 5000, 10000]
    kernel_r = ["rbf"]
    #gamma_r = [0.5, 1]
    gamma_r = [1]
    
    coef = 0
    rs = 42
    z = np.zeros(47)
    itr = 1

    M_train = inputDB_train
    M_val = inputDB_ext
    M_test = inputDB_ingested
    M_test2 = inputDB_PMdi
    M_ext = inputDB_OldDi

    for c in C_r:
        for k in range(len(kernel_r)):
            for g in gamma_r:

                print("itr=", itr, ", C=", c, ", kernel=", k, ", gamma=", g, ", coef=", coef)
                print("## loading in data ##")
                Xx_train = M_train[M_train.columns[1:-1]]
                Xx_val = M_val[M_val.columns[1:-1]]
                Xx_test = M_test[M_test.columns[1:-1]]
                Xx_test2 = M_test2[M_test2.columns[1:-1]]
                Xx_ext = M_ext[M_ext.columns[1:-1]]
                #
                Yy_train = M_train["type"]
                Yy_val = M_val["type"]
                Yy_test = M_test["type"]
                Yy_test2 = M_test2["type"]
                Yy_ext = M_ext["type"]
                print("## Classification ##")
                model_svm = SVC(
                    kernel = kernel_r[k],
                    C=c, 
                    gamma = g,
                    random_state=42, 
                    class_weight={0:0.7494, 1:0.8700, 2:1.9369})


                # Training Set
                model_svm.fit(Xx_train, Yy_train)

                importances = permutation_importance(model_svm, Xx_test, Yy_test, n_repeats=10, random_state=42, n_jobs=-1)
                #print(importances["importances_mean"])

                if itr == 1:
                    z[0] = c
                    z[1] = k
                    z[2] = g
                    z[3] = coef
                    z[4] = f1_score(Yy_train, model_svm.predict(Xx_train), average='weighted', sample_weight=sampleW)
                    z[5] = matthews_corrcoef(Yy_train, model_svm.predict(Xx_train), sample_weight=sampleW)
                    z[6] = f1_score(Yy_val, model_svm.predict(Xx_val), average='weighted', sample_weight=sampleExtW)
                    z[7] = matthews_corrcoef(Yy_val, model_svm.predict(Xx_val), sample_weight=sampleExtW)
                    print("## No CV ##")
                    scores_SVM = cross_val_score(model_svm, nn_train, mm_train, cv=5, scoring = "f1")
                    z[8] = scores_SVM.mean()
                    print(scores_SVM.mean())
                    z[9] = f1_score(Yy_test, model_svm.predict(Xx_test), average='weighted', sample_weight=sampleIngestedW)
                    z[10] = matthews_corrcoef(Yy_test, model_svm.predict(Xx_test), sample_weight=sampleIngestedW)
                    z[11] = recall_score(Yy_test, model_svm.predict(Xx_test), average='weighted', sample_weight=sampleIngestedW)
                    z[12] = f1_score(Yy_test2, model_svm.predict(Xx_test2), average='weighted', sample_weight=samplePMDiW)
                    z[13] = matthews_corrcoef(Yy_test2, model_svm.predict(Xx_test2), sample_weight=samplePMDiW)
                    z[14] = recall_score(Yy_test2, model_svm.predict(Xx_test2), average='weighted', sample_weight=samplePMDiW)
                    z[15] = f1_score(Yy_ext, model_svm.predict(Xx_ext), average='weighted', sample_weight=sample3031OldDiW)
                    z[16] = matthews_corrcoef(Yy_ext, model_svm.predict(Xx_ext), sample_weight=sample3031OldDiW)
                    z[17] = recall_score(Yy_ext, model_svm.predict(Xx_ext), average='weighted', sample_weight=sample3031OldDiW)
                    z[18] = rs
                    z[19] = importances["importances_mean"][0]
                    z[20] = importances["importances_mean"][1]
                    z[21] = importances["importances_mean"][2]
                    z[22] = importances["importances_mean"][3]
                    z[23] = importances["importances_mean"][4]
                    z[24] = importances["importances_mean"][5]
                    z[25] = importances["importances_mean"][6]
                    z[26] = importances["importances_mean"][7]
                    z[27] = importances["importances_mean"][8]
                    z[28] = importances["importances_mean"][9]
                    z[29] = importances["importances_mean"][10]
                    z[30] = importances["importances_mean"][11]
                    z[31] = importances["importances_mean"][12]
                    z[32] = importances["importances_mean"][13]
                    z[33] = importances["importances_std"][0]
                    z[34] = importances["importances_std"][1]
                    z[35] = importances["importances_std"][2]
                    z[36] = importances["importances_std"][3]
                    z[37] = importances["importances_std"][4]
                    z[38] = importances["importances_std"][5]
                    z[39] = importances["importances_std"][6]
                    z[40] = importances["importances_std"][7]
                    z[41] = importances["importances_std"][8]
                    z[42] = importances["importances_std"][9]
                    z[43] = importances["importances_std"][10]
                    z[44] = importances["importances_std"][11]
                    z[45] = importances["importances_std"][12]
                    z[46] = importances["importances_std"][13]
                else:
                    itrain = f1_score(Yy_train, model_svm.predict(Xx_train), average='weighted', sample_weight=sampleW)
                    jtrain = matthews_corrcoef(Yy_train, model_svm.predict(Xx_train), sample_weight=sampleW)
                    ival = f1_score(Yy_val, model_svm.predict(Xx_val), average='weighted', sample_weight=sampleExtW)
                    jval = matthews_corrcoef(Yy_val, model_svm.predict(Xx_val), sample_weight=sampleExtW)
                    print("## No CV ##")
                    scores_SVM = cross_val_score(model_svm, nn_train, mm_train, cv=5, scoring = "f1_weighted")
                    traincvtrain = scores_SVM.mean()
                    f1s = f1_score(Yy_test, model_svm.predict(Xx_test), average='weighted', sample_weight=sampleIngestedW)
                    mccs = matthews_corrcoef(Yy_test, model_svm.predict(Xx_test), sample_weight=sampleIngestedW)
                    rec = recall_score(Yy_test, model_svm.predict(Xx_test), average='weighted', sample_weight=sampleIngestedW)
                    f1s2 = f1_score(Yy_test2, model_svm.predict(Xx_test2), average='weighted', sample_weight=samplePMDiW)
                    mccs2 = matthews_corrcoef(Yy_test2, model_svm.predict(Xx_test2), sample_weight=samplePMDiW)
                    rec2 = recall_score(Yy_test2, model_svm.predict(Xx_test2), average='weighted', sample_weight=samplePMDiW)
                    f1s3 = f1_score(Yy_ext, model_svm.predict(Xx_ext), average='weighted', sample_weight=sample3031OldDiW)
                    mccs3 = matthews_corrcoef(Yy_ext, model_svm.predict(Xx_ext), sample_weight=sample3031OldDiW)
                    rec3= recall_score(Yy_ext, model_svm.predict(Xx_ext), average='weighted', sample_weight=sample3031OldDiW)
                    im1 = importances["importances_mean"][0]
                    im2 = importances["importances_mean"][1]
                    im3 = importances["importances_mean"][2]
                    im4 = importances["importances_mean"][3]
                    im5 = importances["importances_mean"][4]
                    im6 = importances["importances_mean"][5]
                    im7 = importances["importances_mean"][6]
                    im8 = importances["importances_mean"][7]
                    im9 = importances["importances_mean"][8]
                    im10 = importances["importances_mean"][9]
                    im11 = importances["importances_mean"][10]
                    im12 = importances["importances_mean"][11]
                    im13 = importances["importances_mean"][12]
                    im14 = importances["importances_mean"][13]
                    sd1 = importances["importances_std"][0]
                    sd2 = importances["importances_std"][1]
                    sd3 = importances["importances_std"][2]
                    sd4 = importances["importances_std"][3]
                    sd5 = importances["importances_std"][4]
                    sd6 = importances["importances_std"][5]
                    sd7 = importances["importances_std"][6]
                    sd8 = importances["importances_std"][7]
                    sd9 = importances["importances_std"][8]
                    sd10 = importances["importances_std"][9]
                    sd11 = importances["importances_std"][10]
                    sd12 = importances["importances_std"][11]
                    sd13 = importances["importances_std"][12]
                    sd14 = importances["importances_std"][13]
                    tem = np.array([c, k, g, coef, itrain, jtrain, ival, jval, traincvtrain, f1s, mccs, rec, f1s2, mccs2, rec2, f1s3, mccs3, rec3, rs, im1, im2, im3, im4, im5, im6, im7, im8, im9, im10, im11, im12, im13, im14, sd1, sd2, sd3, sd4, sd5, sd6, sd7, sd8, sd9, sd10, sd11, sd12, sd13, sd14])
                    z = np.row_stack([z, tem])
                    #print(z[-1])
                print("End of ", itr, " iterations")
                itr += 1
    z_df = pd.DataFrame(z, columns=["C", "kernel", "gamma", "coef", 
                                    "f1_train", "mcc_train", "f1_fnaVal", "mcc_fnaVal", 
                                    "f1_5Ftrain", "f1_DIn", "mcc_DIn", "recall_DIn", 
                                    "f1_PMDIn", "mcc_PMDIn", "recall_PMDIn", "f1_oldDIn", "mcc_oldDIn", "recall_oldDIn", "state", 
                                    "im1", "im2", "im3", "im4", "im5", "im6", "im7", "im8", "im9", "im10", "im11", "im12", "im13", "im14", 
                                    "sd1", "sd2", "sd3", "sd4", "sd5", "sd6", "sd7", "sd8", "sd9", "sd10", "sd11", "sd12", "sd13", "sd14"])

    return z_df

In [ ]:
## call Gradient Boost ##
optiSearch_df = optimSVMClass(trainDEFSDf, extDEFSDf, ingestedDEFSDf, di1011PMDEFSDf, di3031OldDEFSDf)

itr= 1 , C= 1000 , kernel= 0 , gamma= 1 , coef= 0
## loading in data ##
## Classification ##

In [ ]:
## save ##
optiSearch_df.to_csv(r"I:/4_output_FIBproj/4_3_Output_raMSIn/modeling/hyperparameterTuning_modelSelectionSTD_SVM1.csv")

# 2. Unsupervised Learning

## 2.1. Dataset Preparation

In [42]:
from matplotlib.pyplot import figure
plt.rcParams['figure.figsize'] = [10, 10]
plt.grid(visible=None)
plt.close()
figure(figsize=(10, 10))

In [43]:
df_ROI_for_ML_Opti = pd.concat([trainDEFSDf, extDEFSDf, fnaDEFSDf, diDEFSDf]).set_index('pixel_id')

In [44]:
df_ROI_for_ML_Opti_ingested = ingestedDEFSDf.set_index('pixel_id')

In [45]:
df_ROI_for_ML_Opti_train = trainDEFSDf.set_index('pixel_id')

In [46]:
df_ROI_for_ML_Opti_ext = extDEFSDf.set_index('pixel_id')

In [47]:
df_ROI_for_ML_Opti_FNA = fnaDEFSDf.set_index('pixel_id')

In [48]:
df_ROI_for_ML_Opti_di = diDEFSDf.set_index('pixel_id')

In [49]:
df_ROI_for_ML_Opti_di.describe()

,250.1448,303.2329,295.2278,480.3099,215.0326,255.233,327.233,619.2894,865.5025,311.1688,269.2486,738.5062,435.2964,514.2848,type
count,1.245700e+04,1.245700e+04,1.245700e+04,1.245700e+04,1.245700e+04,1.245700e+04,1.245700e+04,1.245700e+04,1.245700e+04,1.245700e+04,1.245700e+04,1.245700e+04,1.245700e+04,1.245700e+04,12457.000000
mean,-3.220600e-16,1.200684e-16,6.445479e-17,2.645213e-16,5.510742e-16,1.156479e-16,2.566784e-17,3.229869e-16,-3.372468e-16,2.730773e-16,-1.249168e-16,4.734290e-17,-1.518110e-15,2.651274e-16,0.704182
std,9.999197e-01,9.999197e-01,9.999197e-01,9.999197e-01,9.999197e-01,9.999197e-01,9.999197e-01,9.999197e-01,9.999197e-01,9.999197e-01,9.999197e-01,9.999197e-01,9.999197e-01,9.999197e-01,0.783322
min,-7.425172e-01,-3.109601e+00,-1.899695e+00,-3.098025e+00,-2.060723e+00,-4.249083e+00,-3.390606e+00,-3.940131e+00,-2.565252e+00,-3.329106e+00,-4.230758e+00,-2.762536e+00,-1.759569e+00,-2.052358e+00,0.000000
25%,-5.805954e-01,-3.375786e-01,-3.373794e-01,-3.036085e-01,-7.340099e-01,-2.967972e-01,-3.118136e-01,-3.106610e-01,-3.783508e-01,-2.919331e-01,-2.508401e-01,-3.253968e-01,-6.227366e-01,-3.562166e-01,0.000000
50%,-5.576841e-01,-3.606340e-02,-1.278303e-01,2.283880e-02,-4.464153e-02,-1.034354e-01,-2.025641e-02,1.893570e-02,-8.118439e-02,-2.780252e-02,-9.481029e-02,-1.031256e-02,5.484875e-02,-1.854557e-01,1.000000
75%,5.810085e-01,2.151242e-01,1.404423e-01,2.379154e-01,4.307611e-01,1.468193e-01,2.352058e-01,2.617613e-01,2.495826e-01,1.832439e-01,1.056384e-01,2.461702e-01,3.830242e-01,1.220656e-01,1.000000
max,2.204282e+01,2.357956e+01,2.681432e+01,2.063221e+01,2.173711e+01,2.231962e+01,1.996261e+01,1.857949e+01,2.147378e+01,2.037635e+01,2.249389e+01,1.763010e+01,2.117332e+01,4.917368e+01,2.000000

In [50]:
df_ROI_for_ML_Opti_pm = di1011PMDEFSDf.set_index('pixel_id')

In [51]:
df_ROI_for_ML_Opti_pm.describe()

,250.1448,303.2329,295.2278,480.3099,215.0326,255.233,327.233,619.2894,865.5025,311.1688,269.2486,738.5062,435.2964,514.2848,type
count,3.364000e+03,3.364000e+03,3.364000e+03,3.364000e+03,3.364000e+03,3.364000e+03,3.364000e+03,3.364000e+03,3.364000e+03,3.364000e+03,3.364000e+03,3.364000e+03,3.364000e+03,3.364000e+03,3364.000000
mean,-1.292499e-15,1.001313e-16,-3.743156e-16,-5.017456e-16,1.024547e-15,4.156406e-16,7.174123e-16,-1.500309e-16,-7.547140e-16,-9.825672e-16,9.623693e-17,1.277549e-15,2.388102e-16,1.619130e-16,0.502675
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.500067
min,-3.693297e-01,-4.315323e+00,-2.564074e+00,-3.464352e+00,-8.106367e-01,-3.824225e+00,-4.229888e+00,-3.563928e+00,-1.872709e+00,-2.776279e+00,-4.643272e+00,-2.771118e+00,-2.445294e+00,-1.120593e+00,0.000000
25%,-3.693297e-01,-4.604013e-01,-7.178545e-01,-4.205893e-01,-8.106367e-01,-5.027530e-01,-3.949797e-01,-4.387933e-01,-5.028309e-01,-5.697520e-01,-6.150722e-01,-5.896198e-01,-3.804664e-01,-5.805891e-01,0.000000
50%,-3.693297e-01,5.378732e-02,-1.691486e-01,6.363037e-02,-8.106367e-01,5.567795e-02,1.497357e-02,-5.493049e-02,-3.798656e-02,-7.953535e-02,-4.387516e-02,-2.931083e-03,9.637199e-02,-4.385500e-01,1.000000
75%,-3.693297e-01,5.731078e-01,5.775301e-01,5.179167e-01,7.165604e-01,5.941939e-01,5.017800e-01,4.718180e-01,6.014612e-01,8.086186e-01,5.820606e-01,6.743050e-01,6.434105e-01,8.454862e-02,1.000000
max,4.817235e+00,3.828461e+00,4.671473e+00,3.728492e+00,3.635248e+00,3.707653e+00,4.722647e+00,3.785658e+00,5.813256e+00,2.761711e+00,4.329884e+00,3.449741e+00,3.004527e+00,3.933071e+00,1.000000

## 2.2. PCA Analysis

In [ ]:
## PCA Analysis

def pca_visual(df=df_ROI_for_ML_Opti_c):

    pca = PCA(n_components=3)
    raMSI_ML_mz_df = df.drop("type", axis = 1)
    pca.fit(raMSI_ML_mz_df)
    result = pd.DataFrame(pca.transform(raMSI_ML_mz_df), columns=['PCA%i' % i for i in range(3)], index=df_ROI_for_ML_Opti_c.index)
    
    plt.subplots(dpi = 300)
    plt.scatter(result['PCA1'], result['PCA2'], c = df['type'], s=1)
    plt.xlabel('PC1', size=20)
    plt.ylabel('PC2', size=20)
    plt.xticks(fontsize=16)
    plt.yticks(fontsize=16)
    #plt.rcParams['figure.figsize'] = [2, 2]
    plt.savefig(r"I:/4_output_FIBproj/4_3_Output_raMSIn_HKU_FIBIngested4ALL/XGB_ALL/afterModelSelection/PCA_c.tif", bbox_inches = 'tight')

    components = pca.fit_transform(raMSI_ML_mz_df)
    total_var = pca.explained_variance_ratio_.sum() * 100
    fig = px.scatter_3d(
        components, x=0, y=1, z=2, color=df['type'],
        title = f'Total Explained Variance: {total_var:.2f}%',
        labels = {'0': 'PC 1', '1': 'PC 2', '2': 'PC 3'}
    )
    fig.show()

pca_visual()

# 3. Supervised Learning

## 3.1. Preparation of training and test dataset

In [52]:
def split_dataset(df=df_ROI_for_ML_Opti_ingested):
    raMSI_ML_NoType = df.drop("type", axis = 1)
    raMSI_ML_Type=df[['type']]
    X_train,X_test,y_train,y_test=train_test_split(raMSI_ML_NoType,raMSI_ML_Type,test_size=0.2,random_state=42)
    return X_train,X_test,y_train,y_test

X_train,X_test,y_train,y_test=split_dataset(df=df_ROI_for_ML_Opti)

In [53]:
X_ingested = df_ROI_for_ML_Opti_ingested[df_ROI_for_ML_Opti_ingested.columns[:-1]]

In [54]:
y_ingested = df_ROI_for_ML_Opti_ingested[df_ROI_for_ML_Opti_ingested.columns[-1]]

In [55]:
X_train = df_ROI_for_ML_Opti_train[df_ROI_for_ML_Opti_train.columns[:-1]]

In [56]:
y_train = df_ROI_for_ML_Opti_train[df_ROI_for_ML_Opti_train.columns[-1]]

In [57]:
df_ROI_for_ML_Opti_train2 = pd.concat([df_ROI_for_ML_Opti_train, df_ROI_for_ML_Opti_train.loc[df_ROI_for_ML_Opti_train["type"] == 2]]).reset_index().set_index('pixel_id')

In [58]:
X_train_ = df_ROI_for_ML_Opti_train2[df_ROI_for_ML_Opti_train2.columns[:-1]]

In [59]:
y_train_ = df_ROI_for_ML_Opti_train2[df_ROI_for_ML_Opti_train2.columns[-1]]

In [60]:
X_val = df_ROI_for_ML_Opti_ext[df_ROI_for_ML_Opti_ext.columns[:-1]]

In [61]:
y_val = df_ROI_for_ML_Opti_ext[df_ROI_for_ML_Opti_ext.columns[-1]]

In [62]:
X_FNA = df_ROI_for_ML_Opti_FNA[df_ROI_for_ML_Opti_FNA.columns[:-1]]

In [63]:
y_FNA = df_ROI_for_ML_Opti_FNA[df_ROI_for_ML_Opti_FNA.columns[-1]]

In [64]:
X_di = df_ROI_for_ML_Opti_di[df_ROI_for_ML_Opti_di.columns[:-1]]

In [65]:
y_di = df_ROI_for_ML_Opti_di[df_ROI_for_ML_Opti_di.columns[-1]]

In [66]:
X_pm = df_ROI_for_ML_Opti_pm[df_ROI_for_ML_Opti_pm.columns[:-1]]

In [67]:
y_pm = df_ROI_for_ML_Opti_pm[df_ROI_for_ML_Opti_pm.columns[-1]]

## 3.2 Machine Learning Modeling: Model 1+2 (Train 10:10, Val 4:4, Test 3:3)

In [68]:
from matplotlib.pyplot import figure
plt.rcParams['figure.figsize'] = [10, 10]
plt.grid(visible=None)
plt.close()
figure(figsize=(10, 10))

### 3.2.1. GBM

In [69]:
## Build GBM Model
from sklearn.ensemble import GradientBoostingClassifier

def GBM_func(XTrain=X_train_, XVal=X_val, XTest=X_ingested, yTrain=y_train_, yVal=y_val, yTest=y_ingested):
    model_gbm = GradientBoostingClassifier(learning_rate=5, n_estimators=50, max_depth=12, min_samples_leaf=8, min_samples_split=30, n_iter_no_change=2, random_state=42)
    model_gbm.fit(XTrain,yTrain)
    
    # Training Set
    #plt.rcParams["figure.figsize"] = (3,3)
    X_train_predictions = model_gbm.predict(X_train)
    print("Training Set F1:", f1_score(y_train, model_gbm.predict(X_train), average='weighted', sample_weight=sampleW))
    print("Training Set MCC:", matthews_corrcoef(y_train, model_gbm.predict(X_train), sample_weight=sampleW))
    print(classification_report(y_train, X_train_predictions))
    print(confusion_matrix(y_train, X_train_predictions))

    #create ROC curve
    #plt.rcParams['figure.figsize'] = [2, 2]
    #plt.savefig(r"H:/3_2_Output_raMSI_DataIngestion_DESIQE_12F/XGB_FNA/LogReg_ROC_train.tif", bbox_inches = 'tight')
    #plt.show()

    # Val set
    predictions_val  = model_gbm.predict(XVal)
    print("Ext Val Set F1:", f1_score(yVal, model_gbm.predict(XVal), average='weighted', sample_weight=sampleExtW))
    print("Ext Val Set MCC:", matthews_corrcoef(yVal, model_gbm.predict(XVal), sample_weight=sampleExtW))
    print(classification_report(yVal, predictions_val))
    print(confusion_matrix(yVal, predictions_val))

    #create ROC curve
    #plt.rcParams['figure.figsize'] = [2, 2]
    #plt.savefig(r"H:/3_2_Output_raMSI_DataIngestion_DESIQE_12F/XGB_FNA/LogReg_ROC_test.tif", bbox_inches = 'tight')
    #plt.show()
    
    f1_5_train = cross_val_score(model_gbm, XTrain, yTrain, cv = 5, scoring="f1_macro")
    print("5F-CV:", avgScore(f1_5_train, 5))
    
    # Test set
    predictions_ingested = model_gbm.predict(XTest)
    print("Ingested Set F1:", f1_score(yTest, model_gbm.predict(XTest), average='weighted', sample_weight=sampleIngestedW))
    print("Ingested Set MCC:", matthews_corrcoef(yTest, model_gbm.predict(XTest), sample_weight=sampleIngestedW))
    print("Ingested Set Recall:", recall_score(yTest, model_gbm.predict(XTest), average='weighted'))
    print(classification_report(yTest, predictions_ingested))
    print(confusion_matrix(yTest, predictions_ingested))

    #create ROC curve
    #plt.rcParams['figure.figsize'] = [2, 2]
    #plt.savefig(r"G:/raMSIn/XGB_Importance2/XGB2_ROC_FNAtest2.tif", bbox_inches = 'tight')
    #plt.show()
    
    # Visualize the importantance of the features
    feature_imp = pd.Series(model_gbm.feature_importances_, index=XTrain.columns).sort_values(ascending=False)
    x=feature_imp
    y=feature_imp.index
    
    plt.subplots(dpi = 300)
    #plt.rcParams["figure.figsize"] = [4, 6]
    #plt.rcParams["font.family"] = "Arial"
    #plt.rcParams.update({'font.size': 6})
    plt.xlabel('Feature Importance Score', fontproperties='Arial', fontsize=17)
    plt.ylabel('Features', fontproperties='Arial', fontsize=17)
    plt.xticks(fontsize=15)
    plt.yticks(fontsize=15)
    plt.title("Important Molecular Features", fontproperties='Arial', fontsize=20)
    sns.barplot(x=feature_imp, y=feature_imp.index)
    #plt.savefig(r"H:/3_2_Output_raMSI_DataIngestion_DESIQE_12F/XGB_FNA/XGB_TopFeatures.tif", bbox_inches = 'tight')
    #plt.show()

    # Visualize the boxplot of the important features between the two groups
    #fig = px.box(data_frame = df_ROI_for_ML_Opti, x = feature_imp[:10].index,color= 'type')
    #fig.show()
    
    return x, y

In [70]:
coeff_GBM, TOPfeatures_GBM = GBM_func()

Training Set F1: 0.9042245395769064
Training Set MCC: 0.86130037696121
              precision    recall  f1-score   support

           0       0.96      0.80      0.87    198536
           1       0.85      0.94      0.89    171018
           2       0.84      0.98      0.91     76819

    accuracy                           0.89    446373
   macro avg       0.88      0.91      0.89    446373
weighted avg       0.89      0.89      0.88    446373

[[158953  28870  10713]
 [  6781 160724   3513]
 [   694    538  75587]]
Ext Val Set F1: 0.41298248975299895
Ext Val Set MCC: 0.22622417656011698
              precision    recall  f1-score   support

           0       0.60      0.47      0.53     62762
           1       0.53      0.80      0.64     57028
           2       0.33      0.14      0.20     27928

    accuracy                           0.54    147718
   macro avg       0.49      0.47      0.46    147718
weighted avg       0.52      0.54      0.51    147718

[[29756 26499  6507]
 [ 9408 45825  1795]
 [10341 13548  4039]]
5F-CV: 0.818521077201256
Ingested Set F1: 0.5658011715637146
Ingested Set MCC: 0.4217052351872836
Ingested Set Recall: 0.6537500147283833
              precision    recall  f1-score   support

           0       0.77      0.59      0.67    261298
           1       0.58      0.89      0.70    228046
           2       0.70      0.29      0.41    104747

    accuracy                           0.65    594091
   macro avg       0.68      0.59      0.59    594091
weighted avg       0.69      0.65      0.64    594091

[[155464  97702   8132]
 [ 20325 202796   4925]
 [ 25605  49015  30127]]

### 3.2.2. Random Forest

In [69]:
## Build RF Model
from sklearn.ensemble import RandomForestClassifier

def RF_func(XTrain=X_train, XVal=X_val, XTest=X_ingested, yTrain=y_train, yVal=y_val, yTest=y_ingested):
    model_rf = RandomForestClassifier(n_estimators=35, max_depth=3, min_samples_leaf=25, min_samples_split=2, random_state=42, 
                                      n_jobs=-1, oob_score=True,  class_weight={0:0.7494, 1:0.8700, 2:1.9369})
    model_rf.fit(XTrain,yTrain)
    
    # Training Set
    #plt.rcParams["figure.figsize"] = (3,3)
    X_train_predictions = model_rf.predict(X_train)
    print("Training Set F1:", f1_score(y_train, model_rf.predict(X_train), average='weighted', sample_weight=sampleW))
    print("Training Set MCC:", matthews_corrcoef(y_train, model_rf.predict(X_train), sample_weight=sampleW))
    print(classification_report(y_train, X_train_predictions))
    print(confusion_matrix(y_train, X_train_predictions))

    #create ROC curve
    #plt.rcParams['figure.figsize'] = [2, 2]
    #plt.savefig(r"H:/3_2_Output_raMSI_DataIngestion_DESIQE_12F/XGB_FNA/LogReg_ROC_train.tif", bbox_inches = 'tight')
    #plt.show()

    # Val set
    predictions_val  = model_rf.predict(XVal)
    print("Ext Val Set F1:", f1_score(yVal, model_rf.predict(XVal), average='weighted', sample_weight=sampleExtW))
    print("Ext Val Set MCC:", matthews_corrcoef(yVal, model_rf.predict(XVal), sample_weight=sampleExtW))
    print(classification_report(yVal, predictions_val))
    print(confusion_matrix(yVal, predictions_val))

    #create ROC curve
    #plt.rcParams['figure.figsize'] = [2, 2]
    #plt.savefig(r"H:/3_2_Output_raMSI_DataIngestion_DESIQE_12F/XGB_FNA/LogReg_ROC_test.tif", bbox_inches = 'tight')
    #plt.show()
    
    f1_5_train = cross_val_score(model_rf, XTrain, yTrain, cv = 5, scoring="f1_macro")
    print("5F-CV:", avgScore(f1_5_train, 5))
    
    # Test set
    predictions_ingested = model_rf.predict(XTest)
    print("Ingested Set F1:", f1_score(yTest, model_rf.predict(XTest), average='weighted', sample_weight=sampleIngestedW))
    print("Ingested Set MCC:", matthews_corrcoef(yTest, model_rf.predict(XTest), sample_weight=sampleIngestedW))
    print("Ingested Set Recall:", recall_score(yTest, model_rf.predict(XTest), average='weighted'))
    print(classification_report(yTest, predictions_ingested))
    print(confusion_matrix(yTest, predictions_ingested))

    #create ROC curve
    #plt.rcParams['figure.figsize'] = [2, 2]
    #plt.savefig(r"G:/raMSIn/XGB_Importance2/XGB2_ROC_FNAtest2.tif", bbox_inches = 'tight')
    #plt.show()
    
    # Visualize the importantance of the features
    feature_imp = pd.Series(model_rf.feature_importances_, index=XTrain.columns).sort_values(ascending=False)
    x=feature_imp
    y=feature_imp.index
    
    plt.subplots(dpi = 300)
    #plt.rcParams["figure.figsize"] = [4, 6]
    #plt.rcParams["font.family"] = "Arial"
    #plt.rcParams.update({'font.size': 6})
    plt.xlabel('Feature Importance Score', fontproperties='Arial', fontsize=17)
    plt.ylabel('Features', fontproperties='Arial', fontsize=17)
    plt.xticks(fontsize=15)
    plt.yticks(fontsize=15)
    plt.title("Important Molecular Features", fontproperties='Arial', fontsize=20)
    sns.barplot(x=feature_imp, y=feature_imp.index)
    #plt.savefig(r"H:/3_2_Output_raMSI_DataIngestion_DESIQE_12F/XGB_FNA/XGB_TopFeatures.tif", bbox_inches = 'tight')
    #plt.show()

    # Visualize the boxplot of the important features between the two groups
    #fig = px.box(data_frame = df_ROI_for_ML_Opti, x = feature_imp[:10].index,color= 'type')
    #fig.show()
    
    return x, y

In [70]:
coeff_RF, TOPfeatures_RF = RF_func()

Training Set F1: 0.8749706624421404
Training Set MCC: 0.8166466665310792
              precision    recall  f1-score   support

           0       0.89      0.76      0.82    198536
           1       0.81      0.90      0.85    171018
           2       0.85      0.97      0.91     76819

    accuracy                           0.85    446373
   macro avg       0.85      0.88      0.86    446373
weighted avg       0.85      0.85      0.85    446373

[[150620  35651  12265]
 [ 16904 153317    797]
 [  1540    383  74896]]
Ext Val Set F1: 0.6364242701423719
Ext Val Set MCC: 0.5015020769061701
              precision    recall  f1-score   support

           0       0.67      0.81      0.73     62762
           1       0.71      0.77      0.74     57028
           2       0.95      0.37      0.54     27928

    accuracy                           0.71    147718
   macro avg       0.78      0.65      0.67    147718
weighted avg       0.74      0.71      0.70    147718

[[50726 11616   420]
 [13061 43850   117]
 [11560  5945 10423]]
5F-CV: 0.6987456225188929
Ingested Set F1: 0.7185459274250423
Ingested Set MCC: 0.6086490927038141
Ingested Set Recall: 0.7783538212159417
              precision    recall  f1-score   support

           0       0.78      0.79      0.78    261298
           1       0.74      0.89      0.81    228046
           2       0.97      0.49      0.65    104747

    accuracy                           0.78    594091
   macro avg       0.83      0.73      0.75    594091
weighted avg       0.80      0.78      0.77    594091

[[207576  53032    690]
 [ 23968 203156    922]
 [ 36089  16977  51681]]

In [71]:
from matplotlib.pyplot import figure
plt.rcParams['figure.figsize'] = [10, 10]
plt.close()
figure(figsize=(10, 10))

In [72]:
import joblib as jl

In [75]:
models = RandomForestClassifier(n_estimators=35, max_depth=3, min_samples_leaf=25, min_samples_split=2, random_state=42, 
                                n_jobs=-1, oob_score=True,  class_weight={0:0.7494, 1:0.8700, 2:1.9369})
    
models.fit(X_train, y_train)

RandomForestClassifier(class_weight={0: 0.7494, 1: 0.87, 2: 1.9369},
                       max_depth=3, min_samples_leaf=25, n_estimators=35,
                       n_jobs=-1, oob_score=True, random_state=42)

In [76]:
modelSavePath = r"I:\4_output_FIBproj\4_3_Output_raMSIn\modeling\RF_FIBHCC.joblib"
jl.dump(models, modelSavePath, compress = 5)

['I:\\4_output_FIBproj\\4_3_Output_raMSIn\\modeling\\RF_FIBHCC.joblib']

## 4.1 Prediction

In [77]:
## deploy models for training set ##
model_voting = jl.load(r"I:\4_output_FIBproj\4_3_Output_raMSIn\modeling\RF_FIBHCC.joblib")
#
## deploy model ##
predicted0n1_train = model_voting.predict(X_train)
#predicted0n1_trainProba = model_voting.predict_proba(X_train)         
trainDEFSDf["predicted012"] = predicted0n1_train
noRisk_ = []
Risk_ = []
Cancer_ = []
for i in range(len(trainDEFSDf)):
    if trainDEFSDf.iloc[i]["predicted012"] == 0:
        noRisk_.append(1)
        Risk_.append(0)
        Cancer_.append(0)
    elif trainDEFSDf.iloc[i]["predicted012"] == 1:
        noRisk_.append(0)
        Risk_.append(1)
        Cancer_.append(0)
    elif trainDEFSDf.iloc[i]["predicted012"] == 2:
        noRisk_.append(0)
        Risk_.append(0)
        Cancer_.append(1)
trainDEFSDf["noRisk"] = noRisk_
trainDEFSDf["Risk"] = Risk_
trainDEFSDf["Cancer"] = Cancer_
#
## save ##, ouputing trainSet df
savePath = r"I:\4_output_FIBproj\4_3_Output_raMSIn\modeling\df_train_raMSIn_norm_123.csv"
trainDEFSDf.to_csv(savePath)

In [78]:
## deploy models for Ext Val set ##
model_voting = jl.load(r"I:\4_output_FIBproj\4_3_Output_raMSIn\modeling\RF_FIBHCC.joblib")
#
## deploy model ##
predicted0n1_ext = model_voting.predict(X_val)
#predicted0n1_trainProba = model_voting.predict_proba(X_val)         
extDEFSDf["predicted012"] = predicted0n1_ext
noRisk_ = []
Risk_ = []
Cancer_ = []
for i in range(len(extDEFSDf)):
    if extDEFSDf.iloc[i]["predicted012"] == 0:
        noRisk_.append(1)
        Risk_.append(0)
        Cancer_.append(0)
    elif extDEFSDf.iloc[i]["predicted012"] == 1:
        noRisk_.append(0)
        Risk_.append(1)
        Cancer_.append(0)
    elif extDEFSDf.iloc[i]["predicted012"] == 2:
        noRisk_.append(0)
        Risk_.append(0)
        Cancer_.append(1)
extDEFSDf["noRisk"] = noRisk_
extDEFSDf["Risk"] = Risk_
extDEFSDf["Cancer"] = Cancer_
#
## save ##, ouputing extSet df
savePath = r"I:\4_output_FIBproj\4_3_Output_raMSIn\modeling\df_ext_raMSIn_norm_123.csv"
extDEFSDf.to_csv(savePath)

In [79]:
## deploy models for Ingested set ##
model_voting = jl.load(r"I:\4_output_FIBproj\4_3_Output_raMSIn\modeling\RF_FIBHCC.joblib")
#
## deploy model ##
predicted0n1_ingested = model_voting.predict(X_ingested)
#predicted0n1_trainProba = model_voting.predict_proba(X_ingested)         
ingestedDEFSDf["predicted012"] = predicted0n1_ingested
noRisk_ = []
Risk_ = []
Cancer_ = []
for i in range(len(ingestedDEFSDf)):
    if ingestedDEFSDf.iloc[i]["predicted012"] == 0:
        noRisk_.append(1)
        Risk_.append(0)
        Cancer_.append(0)
    elif ingestedDEFSDf.iloc[i]["predicted012"] == 1:
        noRisk_.append(0)
        Risk_.append(1)
        Cancer_.append(0)
    elif ingestedDEFSDf.iloc[i]["predicted012"] == 2:
        noRisk_.append(0)
        Risk_.append(0)
        Cancer_.append(1)
ingestedDEFSDf["noRisk"] = noRisk_
ingestedDEFSDf["Risk"] = Risk_
ingestedDEFSDf["Cancer"] = Cancer_
#
## save ##, ouputing extSet df
savePath = r"I:\4_output_FIBproj\4_3_Output_raMSIn\modeling\df_ingested_raMSIn_norm_123.csv"
ingestedDEFSDf.to_csv(savePath)

In [80]:
## deploy models for PMDIn set ##
model_voting = jl.load(r"I:\4_output_FIBproj\4_3_Output_raMSIn\modeling\RF_FIBHCC.joblib")
#
## deploy model ##
predicted0n1_PM = model_voting.predict(X_pm)
#predicted0n1_trainProba = model_voting.predict_proba(X_pm)         
di1011PMDEFSDf["predicted012"] = predicted0n1_PM
noRisk_ = []
Risk_ = []
Cancer_ = []
for i in range(len(di1011PMDEFSDf)):
    if di1011PMDEFSDf.iloc[i]["predicted012"] == 0:
        noRisk_.append(1)
        Risk_.append(0)
        Cancer_.append(0)
    elif di1011PMDEFSDf.iloc[i]["predicted012"] == 1:
        noRisk_.append(0)
        Risk_.append(1)
        Cancer_.append(0)
    elif di1011PMDEFSDf.iloc[i]["predicted012"] == 2:
        noRisk_.append(0)
        Risk_.append(0)
        Cancer_.append(1)
di1011PMDEFSDf["noRisk"] = noRisk_
di1011PMDEFSDf["Risk"] = Risk_
di1011PMDEFSDf["Cancer"] = Cancer_
#
## save ##, ouputing extSet df
savePath = r"I:\4_output_FIBproj\4_3_Output_raMSIn\modeling\df_PMDIn_raMSIn_norm_123.csv"
di1011PMDEFSDf.to_csv(savePath)

In [81]:
di1011PMDEFSDf

,pixel_id,250.1448,303.2329,295.2278,480.3099,215.0326,255.233,327.233,619.2894,865.5025,311.1688,269.2486,738.5062,435.2964,514.2848,type,predicted012,noRisk,Risk,Cancer
0,HKBULiver_Halfyear_FibrosisAMCLiver_DirectIn_M...,-0.36933,0.088734,0.452591,0.624357,0.744042,0.345283,0.982864,0.291689,1.040174,0.290187,-0.094526,0.321747,0.085217,-0.445423,0,1,0,1,0
1,HKBULiver_Halfyear_FibrosisAMCLiver_DirectIn_M...,-0.36933,-0.201833,0.604872,0.460051,-0.810637,0.452955,0.308910,0.058328,0.686840,0.182935,0.328750,0.392576,-0.114069,-0.484110,0,1,0,1,0
2,HKBULiver_Halfyear_FibrosisAMCLiver_DirectIn_M...,-0.36933,-0.164687,0.249824,0.892365,0.782306,0.048529,0.107290,-0.656984,0.663825,-0.113763,0.823456,0.112642,-1.114433,-0.465705,0,0,1,0,0
3,HKBULiver_Halfyear_FibrosisAMCLiver_DirectIn_M...,-0.36933,-0.097753,0.731184,0.541603,-0.810637,0.430904,0.704984,-0.434250,1.963588,-0.037164,0.561729,1.260449,0.465858,-0.494882,0,0,1,0,0
4,HKBULiver_Halfyear_FibrosisAMCLiver_DirectIn_M...,-0.36933,-0.602424,0.280637,-0.087438,0.419113,-0.318601,-0.163125,-0.861845,-0.297223,-0.306744,-0.131589,-0.793509,-0.441613,-0.510262,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3359,HKBULiver_Halfyear_FibrosisLiver_DirectIn_Mice...,-0.36933,0.200524,-0.647980,0.233060,-0.810637,0.765507,0.191102,-0.075249,-0.218766,1.475244,0.340192,-0.500204,0.509061,-0.627430,1,1,0,1,0
3360,HKBULiver_Halfyear_FibrosisLiver_DirectIn_Mice...,-0.36933,0.344717,-0.208700,0.423365,-0.810637,1.252085,0.132593,0.278179,-0.036554,1.534465,1.317275,-0.826349,-0.141638,-0.623744,1,1,0,1,0
3361,HKBULiver_Halfyear_FibrosisLiver_DirectIn_Mice...,-0.36933,0.349257,-0.228705,0.880851,0.195907,1.383750,0.084254,0.416100,0.537164,1.555862,0.725883,0.813694,0.337516,-0.652096,1,1,0,1,0
3362,HKBULiver_Halfyear_FibrosisLiver_DirectIn_Mice...,-0.36933,-0.221511,-0.812250,-0.337346,-0.810637,0.318545,-0.159116,0.150794,-0.189410,1.157331,-0.444499,-0.251843,-0.059958,-0.658126,1,1,0,1,0
3363,HKBULiver_Halfyear_FibrosisLiver_DirectIn_Mice...,-0.36933,0.255189,0.029164,0.727502,-0.810637,1.681617,-0.078589,-0.025528,0.698174,1.336357,1.571974,1.320346,-0.884968,-0.647519,1,1,0,1,0